-- =========================================================================
-- MASTER MIGRATION: PDC V3 INTEGRAL UPDATE
-- Date: 2026-03-03
-- Description: Consolidates all changes made today:
-- 1. Create theoretical library (biblioteca_teoria)
-- 2. Drop obsolete legacy tables
-- 3. Create 8 new detail tables linked to semana_contenido
-- =========================================================================

-- 1. CREATE BIBLIOTECA_TEORIA (Global Library)
CREATE TABLE IF NOT EXISTS public.biblioteca_teoria (
    id_teoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_estrategia_teorica TEXT NOT NULL,
    proposito TEXT,
    tipo TEXT,
    apto_para TEXT,
    descripcion_concreta TEXT,
    redactado BOOLEAN DEFAULT FALSE,
    ejemplo_inicial TEXT,
    ejemplo_primaria TEXT,
    ejemplo_secundaria TEXT,
    ejemplo_multigrado TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.biblioteca_teoria ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'biblioteca_teoria' AND policyname = 'Public read access for biblioteca_teoria') THEN
        CREATE POLICY "Public read access for biblioteca_teoria" ON public.biblioteca_teoria FOR SELECT TO authenticated USING (true);
    END IF;
END $$;

-- 2. DROP OBSOLETE LEGACY TABLES
DROP TABLE IF EXISTS public.adaptaciones CASCADE;
DROP TABLE IF EXISTS public.momentos CASCADE;
DROP TABLE IF EXISTS public.semana_recurso CASCADE;
DROP TABLE IF EXISTS public.recursos CASCADE;
DROP TABLE IF EXISTS public.tipos_recurso CASCADE;

-- 3. CREATE PLANNING DETAIL TABLES (1:N with semana_contenido)

-- 3.1. Table: PRACTICA
CREATE TABLE IF NOT EXISTS public.practica (
    id_practica BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semana_contenido_id UUID NOT NULL REFERENCES public.semana_contenido(id) ON DELETE CASCADE,
    nombre_practica TEXT NOT NULL,
    proposito TEXT,
    tipo TEXT,
    apto_para TEXT,
    descripcion TEXT,
    redactado BOOLEAN DEFAULT FALSE,
    preguntas TEXT,
    ejemplo_inicial TEXT,
    ejemplo_primaria TEXT,
    ejemplo_secundaria TEXT,
    ejemplo_multigrado TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3.2. Table: TEORIA
CREATE TABLE IF NOT EXISTS public.teoria (
    id_teoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semana_contenido_id UUID NOT NULL REFERENCES public.semana_contenido(id) ON DELETE CASCADE,
    nombre_estrategia_teorica TEXT NOT NULL,
    proposito TEXT,
    tipo TEXT,
    apto_para TEXT,
    descripcion_concreta TEXT,
    redactado BOOLEAN DEFAULT FALSE,
    ejemplo_inicial TEXT,
    ejemplo_primaria TEXT,
    ejemplo_secundaria TEXT,
    ejemplo_multigrado TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3.3. Table: PRODUCTO
CREATE TABLE IF NOT EXISTS public.producto (
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semana_contenido_id UUID NOT NULL REFERENCES public.semana_contenido(id) ON DELETE CASCADE,
    nombre_producto TEXT NOT NULL,
    descripcion_concreta TEXT,
    nivel TEXT,
    subnivel TEXT,
    tipo TEXT,
    redactado BOOLEAN DEFAULT FALSE,
    instrumento TEXT,
    ejemplo_inicial TEXT,
    ejemplo_primaria TEXT,
    ejemplo_secundaria TEXT,
    ejemplo_multigrado TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3.4. Table: VALORACION
CREATE TABLE IF NOT EXISTS public.valoracion (
    id_valoracion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semana_contenido_id UUID NOT NULL REFERENCES public.semana_contenido(id) ON DELETE CASCADE,
    categoria TEXT,
    preguntas TEXT,
    redactado BOOLEAN DEFAULT FALSE,
    instrumento TEXT,
    ejemplo_inicial TEXT,
    ejemplo_primaria TEXT,
    ejemplo_secundaria TEXT,
    ejemplo_multigrado TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3.5. Table: RECURSOS (Instanced)
CREATE TABLE IF NOT EXISTS public.recursos (
    id_recursos BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semana_contenido_id UUID NOT NULL REFERENCES public.semana_contenido(id) ON DELETE CASCADE,
    tipo TEXT,
    recursos TEXT,
    ejemplo TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3.6. Table: SER
CREATE TABLE IF NOT EXISTS public.ser (
    id_ser BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semana_contenido_id UUID NOT NULL REFERENCES public.semana_contenido(id) ON DELETE CASCADE,
    categoria TEXT,
    subcategoria TEXT,
    nombre_ser TEXT NOT NULL,
    descripcion TEXT,
    redactado BOOLEAN DEFAULT FALSE,
    instrumento_sugerido TEXT,
    dificultad TEXT,
    ejemplo_inicial TEXT,
    ejemplo_primaria TEXT,
    ejemplo_secundaria TEXT,
    ejemplo_multigrado TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3.7. Table: SABER
CREATE TABLE IF NOT EXISTS public.saber (
    id_saber BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semana_contenido_id UUID NOT NULL REFERENCES public.semana_contenido(id) ON DELETE CASCADE,
    nivel TEXT,
    subnivel TEXT,
    verbo_saber TEXT NOT NULL,
    redactado BOOLEAN DEFAULT FALSE,
    evidencia TEXT,
    instrumento_sugerido TEXT,
    dificultad TEXT,
    ejemplo_inicial TEXT,
    ejemplo_primaria TEXT,
    ejemplo_secundaria TEXT,
    ejemplo_multigrado TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3.8. Table: HACER
CREATE TABLE IF NOT EXISTS public.hacer (
    id_hacer BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semana_contenido_id UUID NOT NULL REFERENCES public.semana_contenido(id) ON DELETE CASCADE,
    nivel TEXT,
    subnivel TEXT,
    verbo TEXT NOT NULL,
    redactado BOOLEAN DEFAULT FALSE,
    producto TEXT,
    instrumentos_sugeridos TEXT,
    dificultad TEXT,
    ejemplo_inicial TEXT,
    ejemplo_primaria TEXT,
    ejemplo_secundaria TEXT,
    ejemplo_multigrado TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for all new tables
ALTER TABLE public.practica ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teoria ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.producto ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.valoracion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recursos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ser ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saber ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hacer ENABLE ROW LEVEL SECURITY;

-- Configure RLS Policies
DO $$
DECLARE
    t TEXT;
    table_list TEXT[] := ARRAY['practica', 'teoria', 'producto', 'valoracion', 'recursos', 'ser', 'saber', 'hacer'];
BEGIN
    FOREACH t IN ARRAY table_list
    LOOP
        -- Read Access
        EXECUTE format('DROP POLICY IF EXISTS "Public read access for %I" ON public.%I', t, t);
        EXECUTE format('CREATE POLICY "Public read access for %I" ON public.%I FOR SELECT TO authenticated USING (true)', t, t);
        
        -- Management Access (Professor level)
        EXECUTE format('DROP POLICY IF EXISTS "Teachers can manage their own %I" ON public.%I', t, t);
        EXECUTE format('CREATE POLICY "Teachers can manage their own %I" ON public.%I FOR ALL TO authenticated USING (
            EXISTS (
                SELECT 1 FROM public.semana_contenido sc
                JOIN public.planificacion_semanal ps ON sc.planificacion_semanal_id = ps.id
                JOIN public.areas_trabajo at ON ps.area_trabajo_id = at.id
                WHERE sc.id = semana_contenido_id AND at.profesor_id = auth.uid()
            )
        )', t, t);
    END LOOP;
END $$;
