-- Migration: Create Biblioteca de Prácticas
-- Description: Create a library of pedagogical techniques for the 'Práctica' moment.

CREATE TABLE IF NOT EXISTS biblioteca_practicas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposito TEXT NOT NULL,
    tipo TEXT NOT NULL,
    tecnica TEXT NOT NULL,
    descripcion_concreta TEXT NOT NULL,
    ejemplo_inicial TEXT,
    ejemplo_primaria TEXT,
    ejemplo_secundaria TEXT,
    ejemplo_multigrado TEXT,
    preguntas_generales TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE biblioteca_practicas ENABLE ROW LEVEL SECURITY;

-- Allow read access to all authenticated users
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'biblioteca_practicas' AND policyname = 'Public read access for biblioteca_practicas'
    ) THEN
        CREATE POLICY "Public read access for biblioteca_practicas" ON biblioteca_practicas
            FOR SELECT TO authenticated USING (true);
    END IF;
END $$;
